{% set name = "python-dotenv" %}
{% set version = "0.11.0" %}
{% set sha256 = "8429f459fc041237d98c9ff32e1938e7e5535b5ff24388876315a098027c3a57" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - dotenv = dotenv:cli.cli

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - click >=5.0

test:
  imports:
    - dotenv

about:
  home: https://github.com/theskumar/python-dotenv/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Get and set values in your .env file in local and production servers like Heroku does.'
  dev_url: https://github.com/theskumar/python-dotenv/

extra:
  recipe-maintainers:
    - proinsias
