{% set version = "1.1.0" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: python-dotenv
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python-dotenv/python_dotenv-{{ version }}.tar.gz
  sha256: 41f90bc6f5f177fb41f53e87666db362025010eb28f60a01c9143bfa33a2b2d5

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - dotenv=dotenv.__main__:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - dotenv
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

outputs:
  - name: python-dotenv

  - name: python-dotenv-with-cli
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("python-dotenv", exact=True) }}
        - click >=5.0
    test:
      imports:
        - dotenv
      requires:
        - pip
        - python !={{ python_min }}.*
      commands:
        - pip check
        - dotenv --help

about:
  home: https://saurabh-kumar.com/python-dotenv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read key-value pairs from a .env file and set them as environment variables
  dev_url: https://github.com/theskumar/python-dotenv

extra:
  feedstock-name: python-dotenv
  recipe-maintainers:
    - proinsias
    - bollwyvl
