{% set version = "1.0.0" %}

package:
  name: python-dotenv-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-dotenv/python-dotenv-{{ version }}.tar.gz
  sha256: a8df96034aae6d2d50a4ebe8216326c61c3eb64836776504fcca410e5937a3ba

build:
  number: 1
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

outputs:
  - name: python-dotenv-base
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
      entry_points:
        - dotenv=dotenv.__main__:cli
    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - python >=3.8
    test:
      imports:
        - dotenv
      requires:
        - pip
      commands:
        - pip check

  - name: python-dotenv-with-cli
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - {{ pin_subpackage("python-dotenv-base", exact=True) }}
        - click >=5.0
        - python >=3.8
    test:
      imports:
        - dotenv
      requires:
        - pip
      commands:
        - pip check
        - dotenv --help

  - name: python-dotenv
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - {{ pin_subpackage("python-dotenv-base", exact=True) }}
        - {{ pin_subpackage("python-dotenv-with-cli", exact=True) }}
        - python >=3.8
    test:
      imports:
        - dotenv
      requires:
        - pip
      commands:
        - pip check
        - dotenv --help

about:
  home: https://github.com/theskumar/python-dotenv
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read key-value pairs from a .env file and set them as environment variables

extra:
  feedstock-name: python-dotenv
  recipe-maintainers:
    - proinsias
    - bollwyvl
